### ISSUE TITLE
account_id missing from connected response

### ISSUE THREAD

**Issue by Gillinghammer** [catalinmiron/react-native-plaid-link#11]
response metadata is missing account_id

using the test credentials: user_good / pass_good

Is this due to me using sandbox and the test credentials?

**Comment by catalinmiron** [comment]
I think so. Have you tried using development/production keys and got the same result?

**Comment by Gillinghammer** [comment]
Not yet. I’ll give that a go. Super helpful component, just what I needed!

Colin

**Comment by Gillinghammer** [comment]
Gave it a shot switching env to 'development' but now it generates a new error:

"Setting onMessage on a WebView overrides existing values of window.postMessage, 
but a previous value was defined."

Seems the development flow adds a captcha step which must interrupt the expected flow of the onMessage callback.

**Comment by catalinmiron** [comment]
I'll take a look today and hopefully get the fix :) I'll keep this issue open. Thanks!

**Comment by muresanandrei** [comment]
@Gillinghammer An fix for this is 

`renderLogin() {
      const patchPostMessageFunction = () => {
          let originalPostMessage = window.postMessage;
          let patchedPostMessage = function(message, targetOrigin, transfer) {
              originalPostMessage(message, targetOrigin, transfer);
          };

          patchedPostMessage.toString = () => {
              return String(Object.hasOwnProperty).replace(
                  'hasOwnProperty',
                  'postMessage'
              );
          };
          window.postMessage = patchedPostMessage;
      };

      const patchPostMessageJsCode =
          '(' + String(patchPostMessageFunction) + ')();';

    return (
          <PlaidAuthenticator
            onMessage={this.onMessage}
            publicKey="xxxxxxxxxxxxxxxxxx"
            env="development"
            product="auth,transactions"
            clientName="client"
            onLoad={this.onLoad}
            onLoadStart={this.onLoadStart}
            onLoadEnd={this.onLoadEnd}
            requires_code
            includeDisplayData={true}
            javaScriptEnabled={true}
            injectedJavaScript={patchPostMessageJsCode}
          />
    );
  }`
