### ISSUE TITLE
Google recaptcha puzzle was hidden

### ISSUE THREAD

**Issue by noootown** [catalinmiron/react-native-plaid-link#31]
Not sure if anybody face this problem. I used IPhone XS Max to implement the link flow on development environment. however, the Recaptcha is blocked by window width. I think this is not the problem of this library, but I still want to ask if anybody has solution to deal with this problem. Thanks!

![Screen Shot 2019-10-02 at 11 28 22 AM](https://user-images.githubusercontent.com/8605020/66016082-cbe7ab00-e507-11e9-851c-58482946b023.png)

**Comment by sebastianpaz** [comment]
I'm having the same problem too. Any thoughts?

**Comment by sebastianpaz** [comment]
It seems to be a Plaid issue since I'm running into the same issue in Safari as well.
![preview2](https://user-images.githubusercontent.com/7588315/69452760-3a472d80-0d41-11ea-964e-61eaf975ac0e.gif)

**Comment by sebastianpaz** [comment]
It seems to be a Plaid problem since I'm running into the same issue in Safari as well.
![preview2](https://user-images.githubusercontent.com/7588315/69452994-c5c0be80-0d41-11ea-8871-62f9105c264c.gif)
